//
//  ViewModelItem.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import Foundation

class ViewModelItem<T: NSObject>: ObservableObject {
    @Published var data: T
    
    required init(data: T) {
        self.data = data
    }
}
