//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//

import UIKit

class ExampleDetailVC: ViewController {

    @IBOutlet weak var photoView: UIImageView!
    @IBOutlet weak var nameLbl: UILabel!
    @IBOutlet weak var detailbl: UILabel!
    
    var viewModel: ExampleItemVM!
    
    /// Array of fields on this viewcontroller
    override var fields: [UITextField] {
        return []
    }
    
    /// Setup add function/ action in object (ex: add button action, add delegate, add gesture)
    override func setupMethod() {
        super.setupMethod()
        
    }
    
    /// Setup layout view
    override func setupView() {
        super.setupView()
        
        photoView.kf.setImage(with: viewModel.photo)
        nameLbl.text = viewModel.name
        detailbl.text = viewModel.detail
    }
        
    /// Get data content
    @objc override func fetch() {
        
    }
}
