//
//  ItemVM.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import Foundation

class ItemVM: ViewModelItem<Item> {
    var name: String {
        data.name
    }
    
    var detail: String {
        data.detail
    }
    
    var imageUrl: URL? {
        URL(string: data.image)
    }
}
