//
//  DetailVC.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import UIKit

class DetailVC: ViewController {

    @IBOutlet weak var imageView: UIImageView!
    @IBOutlet weak var nameLbl: UILabel!
    @IBOutlet weak var detailLbl: UILabel!
    
    var viewModel: ItemVM!
    
    override func setupView() {
        super.setupView()
        
        imageView.kf.setImage(with: viewModel.imageUrl)
        nameLbl.text = viewModel.name
        detailLbl.text = viewModel.detail
    }

}
