//
//  LaunchScreenVC.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import UIKit

class LaunchScreenVC: ViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        startLaunchScreen()
    }
    
    func startLaunchScreen() {
        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 3) {
            guard let vc = AppDelegate.shared.mainController else { return }
            vc.modalPresentationStyle = .fullScreen
            vc.modalTransitionStyle = .crossDissolve
            self.present(vc, animated: true, completion: nil)
        }
    }
}
