//
//  CollectionViewController.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import UIKit

class CollectionViewController: ViewController {
    
    @IBOutlet weak private(set) var collectionView: UICollectionView!
    
    private(set) var refreshControl = UIRefreshControl()
    
    override func setupMethod() {
        super.setupMethod()
        
        collectionView.delegate = self
        collectionView.dataSource = self
        
        refreshControl.addTarget(self, action: #selector(fetch), for: .valueChanged)
    }
    
    override func setupView() {
        super.setupView()
        
        collectionView.addSubview(refreshControl)
    }
    
    @objc override func fetch() {
        super.fetch()
        
        fetch(isLoadMore: false)
    }
    
    /// Fetch list data
    @objc func fetch(isLoadMore: Bool = false) {
        
    }
    
    var backgroundView: UIView? {
        if collectionView(collectionView, numberOfItemsInSection: 0) <= 0 {
            if isLoading {
                return LoadIndicatorView()
            }
            return ErrorView(message: L10n.Error.dataNotFound)
        }
        return nil
    }
    
    /// Footer view of table view
    var footerView: UIView? {
        if isAllowLoadMore {
            let frame = CGRect(x: 0, y: 0, width: collectionView.frame.width, height: 50)
            let loadingView = LoadIndicatorView()
            loadingView.frame = frame
            return loadingView
        }
        return UIView(frame: .zero)
    }
}

extension CollectionViewController {
    @objc open var isLoading: Bool {
        false
    }
    
    /// Indicate that list can load more
    @objc open var isAllowLoadMore: Bool {
        false
    }
    
    /// Distance from bottom to trigger load more
    @objc open var loadMoreDistance: CGFloat {
        40
    }
}

extension CollectionViewController: UICollectionViewDataSource {
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        fatalError("Number items method not defined")
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        fatalError("Cell collectionView not set")
    }
}

extension CollectionViewController: UICollectionViewDelegate {
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        let offset = scrollView.contentOffset
        let bounds = scrollView.bounds
        let size = scrollView.contentSize
        let inset = scrollView.contentInset
        let y = offset.y + bounds.size.height - inset.bottom
        let h = size.height
        if y > (h + loadMoreDistance) {
            if isAllowLoadMore {
                fetch(isLoadMore: true)
            }
        }
    }
}
