//
//  CollectionViewController.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import UIKit

class CollectionViewController: ViewController {
    
    @IBOutlet weak private(set) var collectionView: UICollectionView!
    
    private(set) var refreshControl = UIRefreshControl()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        registerCell()
        setupMethod()
        setupView()
    }
    
    func registerCell() {
        
    }
    
    override func setupMethod() {
        super.setupMethod()
        
        collectionView.delegate = self
        collectionView.dataSource = self
        
        refreshControl.addTarget(self, action: #selector(refresh), for: .valueChanged)
    }
    
    override func setupView() {
        super.setupView()
        
        collectionView.addSubview(refreshControl)
    }
    
    @objc private func refresh() {
        Task {
            await fetch()
        }
    }
    
    @objc override func fetch() async {
        await fetch(isLoadMore: false)
    }
    
    /// Fetch list data
    @objc func fetch(isLoadMore: Bool = false) async {
        
    }
    
    var loadingView: UIView? {
        if collectionView(collectionView, numberOfItemsInSection: 0) <= 0 {
            let loadingView = LoadIndicatorView()
            loadingView.startAnimating()
            return loadingView
        }
        return nil
    }
    
    var errorView: UIView? {
        if collectionView(collectionView, numberOfItemsInSection: 0) <= 0 {
            return ErrorView(message: L10n.Error.dataNotFound)
        }
        return nil
    }
    
    /// Footer view of table view
    var loadMoreView: UIView? {
        if isAllowLoadMore {
            let frame = CGRect(x: 0, y: 0, width: collectionView.frame.width, height: 50)
            let loadingView = LoadIndicatorView()
            loadingView.startAnimating()
            loadingView.frame = frame
            return loadingView
        }
        return UIView(frame: .zero)
    }
    
    func fitItemSize(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumSize: CGSize, minimumColumn: Int) -> CGSize {
        let flowLayout = collectionViewLayout as? UICollectionViewFlowLayout
        let horizontalMargin = (flowLayout?.sectionInset.left ?? 0) + (flowLayout?.sectionInset.right ?? 0)
        let spacing = flowLayout?.minimumInteritemSpacing ?? 0.0
        
        let contentWidth = (collectionView.frame.width - horizontalMargin)
        let maxItem = CGFloat(max(minimumColumn, Int(contentWidth / minimumSize.width)))
        let newWidth = (contentWidth - (spacing * (maxItem - 1))) / maxItem
        let newHeight = minimumSize.height * newWidth / minimumSize.width
        return CGSize(width: newWidth, height: newHeight)
    }
}

extension CollectionViewController {
    /// Indicate that list can load more
    @objc open var isAllowLoadMore: Bool {
        false
    }
    
    /// Distance from bottom to trigger load more
    @objc open var loadMoreDistance: CGFloat {
        50
    }
}

extension CollectionViewController: UICollectionViewDataSource {
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        0
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        fatalError("Cell collectionView not set")
    }
    
    
}

extension CollectionViewController: UICollectionViewDelegate {
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        let offset = scrollView.contentOffset
        let bounds = scrollView.bounds
        let size = scrollView.contentSize
        let inset = scrollView.contentInset
        let y = offset.y + bounds.size.height - inset.bottom
        let h = size.height
        if y > (h + loadMoreDistance) {
            if isAllowLoadMore {
                Task {
                    await fetch(isLoadMore: true)
                }
            }
        }
    }
}
