//
//  AppDelegate.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import UIKit

import NVActivityIndicatorView
import IQKeyboardManagerSwift

// TODO: Need remove if not use firebase
import Firebase

import MMKV

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?
    
    /// INitialize main controller, Change return value with your main menu controller
    func initializeMainController() {
        mainController = StoryboardScene.Main.tabBarMenuVC.instantiate()
        mainController.modalPresentationStyle = .fullScreen
    }
    /// Main view controller
    var mainController: UIViewController!
    
    static var shared: AppDelegate {
        return UIApplication.shared.delegate as! AppDelegate
    }

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        setApp()
        setupView()
        
        // uncomment setupNotification if need push notification
        setupNotification(application: application)
        
        return true
    }
    
    /// Setting all application need
    func setApp() {
        initializeMainController()
        
        MMKV.initialize(rootDir: nil)
        
        SettingsHelper.setupSettings()
        
        KeyboardStateListener.shared.start()
        IQKeyboardManager.shared.enable = true
        IQKeyboardManager.shared.shouldResignOnTouchOutside = true
        
        // TODO: Need remove if not use firebase
        FirebaseApp.configure()
        
        NVActivityIndicatorView.DEFAULT_TYPE = .ballPulse
        
        configureNavigationBar()
        
//        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 5) {
//            fatalError("Test crashlytics")
//        }
    }
    
    func configureNavigationBar() {
        let navigationBarAppearance = UINavigationBar.appearance()
        navigationBarAppearance.shadowImage = UIImage()
        navigationBarAppearance.barTintColor = UIColor.white
        navigationBarAppearance.backgroundColor = UIColor.white
        let attrTitle = [
            NSAttributedString.Key.font: UIFont.boldSystemFont(ofSize: 16),
            NSAttributedString.Key.foregroundColor: Colors.primaryBlack.color
        ]
        navigationBarAppearance.titleTextAttributes = attrTitle
        navigationBarAppearance.tintColor = Colors.primaryBlack.color
        navigationBarAppearance.setBackgroundImage(UIImage(), for: .default)
        navigationBarAppearance.backIndicatorImage = Asset.icBack.image
        navigationBarAppearance.backIndicatorTransitionMaskImage = Asset.icBack.image
        
        if #available(iOS 13.0, *) {
            let appearance = UINavigationBarAppearance()
            appearance.backgroundColor = navigationBarAppearance.backgroundColor
            appearance.titleTextAttributes = attrTitle
            appearance.shadowColor = .clear
            appearance.shadowImage = navigationBarAppearance.shadowImage
            appearance.setBackIndicatorImage(
                navigationBarAppearance.backIndicatorImage,
                transitionMaskImage: navigationBarAppearance.backIndicatorTransitionMaskImage
            )

            UINavigationBar.appearance().standardAppearance = appearance
            UINavigationBar.appearance().scrollEdgeAppearance = appearance
        }
    }
    
    /// Configure root view controller when applicatio open
    func setupView() {
        window?.backgroundColor = UIColor.white
        window?.rootViewController = StoryboardScene.Main.launchScreenVC.instantiate()
    }
    
    /// Setup notification settings
    func setupNotification(application: UIApplication) {
        NotificationHelper.shared.setupNotif(delegate: self, application: application)
    }
    
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        NotificationHelper.shared.register(deviceToken: deviceToken)
    }
    
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        
        NotificationHelper.shared.notificationDidReceive(data: userInfo, fetchCompletionHandler: completionHandler)
    }

    func applicationWillResignActive(_ application: UIApplication) {
        // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
        // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
    }

    func applicationDidEnterBackground(_ application: UIApplication) {
        // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
        // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
    }

    func applicationWillEnterForeground(_ application: UIApplication) {
        // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
    }

    func applicationDidBecomeActive(_ application: UIApplication) {
        // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
    }

    func applicationWillTerminate(_ application: UIApplication) {
        // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
    }
}
