//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//

import Foundation

class ExampleItemVM {
    private var data: ExampleModel
    
    init(data: ExampleModel) {
        self.data = data
    }
    
    var photo: URL? {
        return URL(string: data.image)
    }
    
    var name: String {
        return data.name
    }
    
    var detail: String {
        return data.detail
    }
}
