//
//  KeyboardStateListener.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import Foundation
import UIKit

/// Setting information about keyboard
class KeyboardStateListener: NSObject {
    /// Singleton keyboard manager
    static var shared = KeyboardStateListener()
    /// Boolean value for information keyboard show or hidden
    var isVisible = false
    /// Keyboard frmae
    @objc dynamic var keyboardFrame = CGRect.zero
    
    /// Starting keyboard manager
    func start() {
        let notificationCenter = NotificationCenter.default
        notificationCenter.addObserver(self, selector: #selector(willChangeFrame(_:)), name: UIResponder.keyboardWillChangeFrameNotification, object: nil)
    }
    
    /// Action when keyboard moving show or hide, getting actual size of keyboard
    @objc func willChangeFrame(_ notification: Notification) {
        if let userInfo = notification.userInfo {
            let endFrame = (userInfo[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue)?.cgRectValue
            let screenMain = UIScreen.main.bounds
            if (endFrame?.origin.y)! >= screenMain.size.height {
                isVisible = false
                keyboardFrame = .zero
            } else {
                isVisible = true
                keyboardFrame = endFrame!
            }
        }
    }
}
