//
//  LocationHelper.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import Foundation
import CoreLocation
import UIKit

protocol LocationHelperDelegate: AnyObject {
    func locationHelper(_ helper: LocationHelper, didUpdateLocation location: CLLocation?)
}

class LocationHelper: NSObject {
    static let shared = LocationHelper()
    
    private var locationManager = CLLocationManager()
    @objc dynamic var location: CLLocation?
    
    weak var delegate: LocationHelperDelegate?
    
    override init() {
        super.init()
        
    }
    
    /// Start updating location, location always updating after you start in every view, so if you want to update location in specific view don't forget call stop function
    func start() {
        locationManager.delegate = self
        locationManager.desiredAccuracy = kCLLocationAccuracyBest
        locationManager.requestWhenInUseAuthorization()
        locationManager.startUpdatingLocation()
    }
    
    /// Stop updating location
    func stop() {
        locationManager.stopUpdatingLocation()
    }
    
    /// Restart update location
    @objc func refresh() {
        stop()
        start()
    }
}

extension LocationHelper: CLLocationManagerDelegate {
    func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
        self.location = manager.location
        delegate?.locationHelper(self, didUpdateLocation: self.location)
    }
}
