//
//  ApiParameter.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import Foundation

class ApiParameter {
    let key: String
    let value: Any
    let mimeType: MimeType?
    
    init(key: String, value: Any, mimeType: MimeType? = nil) {
        self.key = key
        self.value = value
        self.mimeType = mimeType
    }
}
