//
//  ApiComponents.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import Foundation
import Alamofire

class ApiComponents {
    private(set) var url: URL
    var method: HTTPMethod
    private var params: [ApiParameter]
    
    init(path: String, method: HTTPMethod, parameters: [ApiParameter] = []) {
        self.url = URL(string: ApiHelper.shared.BASE_URL + path)!
        self.method = method
        self.params = parameters
    }
    
    init(url: URL, method: HTTPMethod, parameters: [ApiParameter] = []) {
        self.url = url
        self.method = method
        self.params = parameters
    }
    
    var parameters: Parameters {
        var params = Parameters()
        params.forEach { param in
            params.updateValue(param.value, forKey: param.key)
        }
        return params
    }
    
    var uploadParameters: UploadParameters {
        var params = UploadParameters()
        self.params.forEach { param in
            params.updateValue(param.value, forKey: param.key, mimeType: param.mimeType)
        }
        return params
    }
}
