//
//  ListVM.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import Foundation
import SwiftyJSON

class ListVM: BaseViewModelList<Item, ItemVM> {
    func fetch(isLoadMore: Bool) async {
        if isLoading {
            return
        }
        if isLoadMore {
            offset = 0
        }
        isLoading = true
        
        // Dummy datas
        guard let url = Bundle.main.url(forResource: "items.json", withExtension: nil) else {
            isLoading = false
            return
        }
        do {
            let data = try Data(contentsOf: url)
            let json = try JSON(data: data)
            let newDatas = json.arrayValue.map({ Item(fromJson: $0) })
            if isLoadMore {
                self.datas.append(contentsOf: newDatas)
            } else {
                self.datas = newDatas
            }
        } catch {
            print("Error parse JSON:", error.localizedDescription)
        }
        isLoading = false
        
        // Example usage of get data
//        await super.fetch(isLoadMore: isLoadMore, path: .exampleGet)
    }
}
