//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//

import Foundation

class ErrorConstant {
    /// Silahkan lengkapi data yang dibutuhkan
    static let completeForm = "Silahkan lengkapi data yang dibutuhkan."
    
    /// Silahkan gunakan email yang valid.
    static let emailValidity = "Silahkan gunakan email yang valid."
    
    /// Silahkan gunakan email yang valid.
    static let passwordLength = "Silahkan gunakan email yang valid."
    
    /// Silahkan masukkan %@
    ///
    /// - Parameter p1: Data that must input
    /// - Returns: Text message and input data
    static func inputData(to p1: String) -> String {
        return "Silahkan masukkan \(p1)."
    }
    
    /// Silahkan pilih %@
    ///
    /// - Parameter p1: Data that must choose
    /// - Returns: Text message and choosen data
    static func chooseData(in p1: String) -> String {
        return "Silahkan pilih \(p1)."
    }
}
