//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//

import Foundation

class Menu {
    /// Type of menu
    ///
    /// - profile: Profile user menu 
    /// - logout: Logout menu
    enum MenuType: Int {
        case home = 0
        case exampleContent = 1
        case profile = 3
        case logout = 4
    }
    
    var type: MenuType
    var id: Int {
        return type.rawValue
    }
    var name: String
    var image: String
    
    init() {
        self.type = .profile
        self.name = ""
        self.image = ""
    }
    
    init(type: MenuType, name: String, image: String) {
        self.type = type
        self.name = name
        self.image = image
    }
}
