//
//  ExtBool.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import Foundation

extension Bool {
    /// Change boolean into integer data type
    var toInt: Int {
        return Int(truncating: NSNumber(value: self))
    }
}
