//
//  ExtUIApplication.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import Foundation
import UIKit

extension UIApplication {
    /// Status bar background view
    var statusBarView: UIView? {
        return value(forKey: "statusBar") as? UIView
    }
    
    func currentActiveController() -> UIViewController? {
        return self.keyWindow?.rootViewController?.currentActiveController()
    }
}

