//
//  ExtString.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import Foundation

extension String {
    /// Check email validity
    var isValidEmail: Bool {
        let emailRegEx = "[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}"
        let emailTest = NSPredicate(format:"SELF MATCHES %@", emailRegEx)
        return emailTest.evaluate(with: self)
    }
    
    /// Check phone number validity
    var isValidPhone: Bool {
        let phoneRegex = "^[0-9+]{0,1}+[0-9]{5,16}$"
        let phoneTest = NSPredicate(format: "SELF MATCHES %@", phoneRegex)
        return phoneTest.evaluate(with: self)
    }
    
    var isValidPassword: Bool {
        let minCharacters = self.count >= 8
        let containsNumber = self.rangeOfCharacter(from: CharacterSet.decimalDigits) != nil
        let containsAlphanumberic = self.rangeOfCharacter(from: CharacterSet.alphanumerics) != nil
        return minCharacters && containsNumber && containsAlphanumberic
    }
    
    var isNotEmpty: Bool {
        !self.isEmpty
    }
    
    /// Change date format to new format date
    ///
    /// - Parameters:
    ///   - old: Current format
    ///   - new: Format that will change
    /// - Returns: New format date
    func dateChange(from old: String, to new: String) -> String {
        if let date = self.date(format: old) {
            let dateFormatter = DateFormatter()
            dateFormatter.locale = LocalizeHelper.shared.locale
            dateFormatter.dateFormat = new
            return dateFormatter.string(from: date)
        }
        return ""
    }
    
    /// Convert string format date to Date data type
    ///
    /// - Parameter format: Current format string date
    /// - Returns: Date from string
    func date(format: String) -> Date? {
        let dateFormatter = DateFormatter()
        dateFormatter.locale = LocalizeHelper.shared.locale
        dateFormatter.dateFormat = format
        if let date = dateFormatter.date(from: self) {
            return date
        }
        return nil
    }
}
