//
//  ExtUIViewController.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import Foundation
import UIKit

extension UIViewController {
    @IBAction func unwindAction(unwindSegue: UIStoryboardSegue) { }
    
    /// Show default simple Alert
    ///
    /// - Parameters:
    ///   - title: Title of alert
    ///   - message: Message of alert
    ///   - handler: Action if alert dismissed
    func simpleAlert(title: String? = nil, message: String, handler: ((UIAlertAction) -> Void)? = nil) {
        let alert = UIAlertController(title: title, message: message, preferredStyle: .alert)
        let ok = UIAlertAction(title: "OK", style: .cancel, handler: handler)
        alert.addAction(ok)
        self.present(alert, animated: true, completion: nil)
    }
    
    func currentActiveController() -> UIViewController {
        if let navigation = self as? UINavigationController {
            return navigation.visibleViewController!.currentActiveController()
        }
        
        if let tab = self as? UITabBarController {
            if let selectedTab = tab.selectedViewController {
                return selectedTab.currentActiveController()
            }
            return tab.currentActiveController()
        }
        
        if self.presentedViewController == nil {
            return self
        }
        if let navigation = self.presentedViewController as? UINavigationController {
            if let visibleController = navigation.visibleViewController {
                return visibleController.currentActiveController()
            }
        }
        if let tab = self.presentedViewController as? UITabBarController {
            if let selectedTab = tab.selectedViewController {
                return selectedTab.currentActiveController()
            }
            return tab.currentActiveController()
        }
        return self.presentedViewController!.currentActiveController()
    }
}
