//
//  ModelData.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import Foundation
import SwiftyJSON

class ModelData: NSObject {
    required init(fromJson json: JSON) {
        
    }
}
