//
//  TabBarMenuVM.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import Foundation
import UIKit
import SwiftUI

class TabBarMenuVM: ObservableObject {
    @Published private(set) var menus = [TabBarMenu]()
    
    init() {
        let home = TabBarMenu(type: .home)
        let table = TabBarMenu(type: .table)
        let collection = TabBarMenu(type: .collection)
        let profile = TabBarMenu(type: .profile)
        let components = TabBarMenu(type: .components)
        menus = [home, table, collection, components, profile]
    }
}
