//
//  Item.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import Foundation
import SwiftyJSON

class Item: BaseModel, Identifiable {
    var detail: String = ""
    var id: Int = 0
    var image: String = ""
    var name: String = ""

    required init(fromJson json: JSON!) {
        super.init(fromJson: json)
        detail = json["detail"].stringValue
        id = json["id"].intValue
        image = json["image"].stringValue
        name = json["name"].stringValue
    }
}
