//
//  TabBarMenu.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import Foundation

class TabBarMenu: Hashable, Identifiable {
    enum TabBarMenuType: Int {
        case home
        case table
        case collection
        case profile
        case components
    }
    
    let type: TabBarMenuType
    let name: String
    let systemImage: String
    
    init(type: TabBarMenuType) {
        self.type = type
        switch type {
        case .home:
            self.name = L10n.Menu.home
            self.systemImage = "house.fill"
        case .table:
            self.name = L10n.Menu.list
            self.systemImage = "list.dash"
        case .collection:
            self.name = L10n.Menu.grid
            self.systemImage = "rectangle.grid.3x2.fill"
        case .components:
            self.name = L10n.Menu.components
            self.systemImage = "folder.fill"
        case .profile:
            self.name = L10n.Menu.profile
            self.systemImage = "person.fill"
        }
    }
    
    var id: TabBarMenuType {
        type
    }
    
    static func == (lhs: TabBarMenu, rhs: TabBarMenu) -> Bool {
        lhs.type == rhs.type
    }
    
    func hash(into hasher: inout Hasher) {
        return hasher.combine(id)
    }
    
}
