//
//  TabBarMenu.swift
//  iOStarter
//
//  Created by Macintosh on 07/04/22.
//  
//
//  This file was generated by Project Xcode Templates
//  Created by Wahyu Ady Prasetyo,
//  Source: https://github.com/dypme/iOStarter
//

import Foundation

class TabBarMenu {
    enum TabBarMenuType {
        case home
        case table
        case collection
        case profile
    }
    
    let type: TabBarMenuType
    let name: String
    
    init(type: TabBarMenuType) {
        self.type = type
        switch type {
        case .home:
            self.name = L10n.Menu.home
        case .table:
            self.name = L10n.Menu.list("1")
        case .collection:
            self.name = L10n.Menu.list("2")
        case .profile:
            self.name = L10n.Menu.profile
        }
    }
}
